import React,{useEffect,useState} from "react";
import{createRoot}from"react-dom/client";
import"./style.css";

const API="http://localhost:8000/api";
const DB="rpl_offline_v2";

function openDB(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;["packages","attempts","evidence","jobs"].forEach(s=>{if(!d.objectStoreNames.contains(s))d.createObjectStore(s,{keyPath:"id"})})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function put(storeName:any,value:any){const d=await openDB();return new Promise<void>((resolve,reject)=>{const t=d.transaction(storeName,"readwrite");t.objectStore(storeName).put(value);t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error)})}
async function get(storeName:any,id:any){const d=await openDB();return new Promise<any>((resolve,reject)=>{const t=d.transaction(storeName,"readonly");const r=t.objectStore(storeName).get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function all(storeName:any){const d=await openDB();return new Promise<any[]>((resolve,reject)=>{const t=d.transaction(storeName,"readonly");const r=t.objectStore(storeName).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}

function App(){
 const[online,setOnline]=useState(navigator.onLine),[stage,setStage]=useState("declare"),[candidate,setCandidate]=useState({name:"",age:18,years_experience:0,occupation:"Construction Electrician",work_context:"",skills:"",prior_training:""}),[job,setJob]=useState<any>(null),[questions,setQuestions]=useState<any[]>([]),[answers,setAnswers]=useState<any>({}),[assessment,setAssessment]=useState<any>(null),[result,setResult]=useState<any>(null),[tasks,setTasks]=useState<any[]>([]),[scores,setScores]=useState<any>({}),[evidence,setEvidence]=useState<any>({}),[error,setError]=useState("");
 useEffect(()=>{const fn=()=>setOnline(navigator.onLine);addEventListener("online",fn);addEventListener("offline",fn);fetch(API+"/practical/tasks").then(r=>r.json()).then(x=>setTasks(x.tasks)).catch(()=>{});return()=>{removeEventListener("online",fn);removeEventListener("offline",fn)}},[]);
 useEffect(()=>{let timer:any;if(job&&online)timer=setInterval(async()=>{const r=await fetch(API+"/jobs/"+job).then(x=>x.json());if(r.status==="completed"){await put("packages",{id:"construction-electrician",questions:r.result.questions});setQuestions(r.result.questions);setJob(null);setStage("test")}if(r.status==="failed")setError(r.error)},1000);return()=>clearInterval(timer)},[job,online]);
 async function generate(){setError("");if(!online){setError("Connect once to download the assessment package, then you can complete it offline.");return}const m=await fetch(API+"/declarations/map",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(candidate)}).then(r=>r.json());if(!m.qp_code){setError("This release supports Construction Electrician - LV. Another trade must be selected by an assessor.");return}const r=await fetch(API+"/jobs/questions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({qp_code:m.qp_code,count:12})}).then(r=>r.json());setJob(r.job_id);setStage("waiting")}
 async function startOffline(){const p=await get("packages","construction-electrician");if(p){setQuestions(p.questions);setStage("test")}else setError("No downloaded assessment package is available offline.")}
 async function capture(task:any){if(!assessment){setError("Submit the theory attempt before attaching evidence.");return}const input=document.createElement("input");input.type="file";input.accept="image/*,video/*";input.capture="environment";input.onchange=async()=>{const f=input.files?.[0];if(!f)return;const id="ev_"+crypto.randomUUID();await put("evidence",{id,assessment_id:assessment,task_id:task.id,name:f.name,type:f.type,blob:f,sync_status:"pending"});setEvidence({...evidence,[task.id]:[...(evidence[task.id]||[]),{id,name:f.name,type:f.type,sync_status:"pending"}]})};input.click()}
 async function submit(){if(Object.keys(answers).length!==questions.length){setError("Answer every question before the single submission.");return}const id="assessment_"+crypto.randomUUID();const payload={assessment_id:id,candidate_id:candidate.name||"offline-candidate",qp_code:"CON/Q0603",candidate,answers:questions.map(q=>({...q,selected_option:answers[q.id]})),practical_scores:tasks.map(t=>scores[t.id]?{task_id:t.id,score:Number(scores[t.id]),max_score:t.max_score,assessor_note:"Captured in assessor workflow"}:null).filter(Boolean)};await put("attempts",{id,payload,sync_status:online?"pending":"queued"});setAssessment(id);setStage("practical");if(online)await syncAttempt(payload)}
 async function syncAttempt(p:any){const r=await fetch(API+"/jobs/evaluation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)}).then(x=>x.json());if(r.accepted===false){setError(r.reason||"Assessment was already submitted.");return}let j;do{await new Promise(x=>setTimeout(x,600));j=await fetch(API+"/jobs/"+r.job_id).then(x=>x.json())}while(j.status==="queued"||j.status==="running");if(j.status!=="completed"){setError(j.error||"Evaluation failed");return}const rr=await fetch(API+"/jobs/recommendation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assessment_id:p.assessment_id,evaluation:j.result})}).then(x=>x.json());do{await new Promise(x=>setTimeout(x,600));j=await fetch(API+"/jobs/"+rr.job_id).then(x=>x.json())}while(j.status==="queued"||j.status==="running");setResult({evaluation:j.result?undefined:j.result,...(j.result||{}),evaluation:j.result?.evaluation||j.result});setStage("result");await put("attempts",{id:p.assessment_id,payload:p,sync_status:"synced",result:j.result})}
 async function finish(){const p=(await get("attempts",assessment))?.payload;if(!p)return;await put("attempts",{id:assessment,payload:p,sync_status:online?"pending":"queued"});if(online)await syncAttempt(p);else setStage("submitted")}
 async function syncEvidence(){if(!online)return;const rows=await all("evidence");for(const x of rows.filter((r:any)=>r.sync_status!=="synced")){const fd=new FormData();fd.append("assessment_id",x.assessment_id);fd.append("task_id",x.task_id);fd.append("media",x.blob,x.name);try{await fetch(API+"/evidence",{method:"POST",body:fd});x.sync_status="synced";await put("evidence",x)}catch{}}}
 useEffect(()=>{if(online){all("attempts").then(xs=>xs.filter(x=>x.sync_status==="queued"||x.sync_status==="pending").forEach(x=>syncAttempt(x.payload)));syncEvidence()}},[online]);
 return <main><header><b>RPL Skill Assessment</b><span>{online?"Online":"Offline"} · Construction Electrician - LV · NSQF 4</span></header>
 {stage==="declare"&&<section><h1>Recognition of Prior Learning</h1><p>Structured self-declaration starts the assessment. AI assists; an authorized assessor makes the final certification decision.</p><input placeholder="Name" value={candidate.name} onChange={e=>setCandidate({...candidate,name:e.target.value})}/><input type="number" placeholder="Age" value={candidate.age} onChange={e=>setCandidate({...candidate,age:+e.target.value})}/><input type="number" placeholder="Years of experience" value={candidate.years_experience} onChange={e=>setCandidate({...candidate,years_experience:+e.target.value})}/><textarea placeholder="Work context and tasks performed" value={candidate.work_context} onChange={e=>setCandidate({...candidate,work_context:e.target.value})}/><textarea placeholder="Prior training/certificates" value={candidate.prior_training} onChange={e=>setCandidate({...candidate,prior_training:e.target.value})}/><button onClick={generate}>Download assessment package</button>{!online&&<button onClick={startOffline}>Use downloaded package</button>}</section>}
 {stage==="waiting"&&<section><h2>Assessment package requested</h2><p>Job <code>{job}</code> is processing asynchronously. The completed package is stored locally for offline use.</p></section>}
 {stage==="test"&&<section><h2>Theory assessment — single attempt</h2>{questions.map((q,i)=><article key={q.id}><small>{i+1}. {q.nos_code} / {q.pc_id}</small><h3>{q.question}</h3>{q.options.map((o,j)=><label key={j}><input type="radio" name={q.id} checked={answers[q.id]===j} onChange={()=>setAnswers({...answers,[q.id]:j})}/>{o}</label>)}</article>)}<button onClick={submit}>Save single attempt</button></section>}
 {stage==="practical"&&<section><h2>Practical evidence and assessor rubric</h2><p>Complete the practical tasks on a safe training setup. Scores are assessor-entered; the worker cannot certify themselves.</p>{tasks.map(t=><article key={t.id}><h3>{t.id} — {t.title}</h3><p>{t.instructions}</p><p><b>Safety:</b> {t.safety}</p>{t.rubric.map((r:any)=><div key={r.criterion}><span>{r.criterion} ({r.weight})</span><input type="number" min="0" max={r.weight} placeholder="Assessor score" onChange={e=>setScores({...scores,[t.id]:Math.min(t.max_score,Number(e.target.value))})}/></div>)}<button onClick={()=>capture(t)}>Capture photo/video evidence</button><small> Evidence: {(evidence[t.id]||[]).length} queued/attached</small></article>)}<button onClick={finish}>Submit for evaluation</button></section>}
 {stage==="submitted"&&<section><h2>Assessment stored locally</h2><p>Assessment ID: <code>{assessment}</code>. Reconnect to sync evaluation, recommendation and evidence.</p></section>}
 {stage==="result"&&result&&<section><h2>AI-assisted assessor recommendation</h2><h1>{result.overall_percentage ?? result.evaluation?.overall_percentage}%</h1><p>{result.provisional_outcome ?? result.evaluation?.provisional_outcome}</p><p>Final authority: human assessor. Evidence authenticity, rubric overrides and certification/sign-off remain assessor-controlled.</p></section>}
 {error&&<p className="error">{error}</p>}</main>
}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
