import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import"./style.css";
const API="http://localhost:8000/api";
function useJob(id){const[d,setD]=useState(null);useEffect(()=>{if(!id)return;const t=setInterval(()=>fetch(API+"/jobs/"+id).then(r=>r.json()).then(x=>{setD(x);if(x.status==="completed"||x.status==="failed")clearInterval(t)}),700);return()=>clearInterval(t)},[id]);return d}
function Worker(){const[c,setC]=useState({name:"",age:25,years_experience:3,occupation:"Construction Electrician",work_context:"",prior_training:""}),[aid,setAid]=useState(""),[job,setJob]=useState(""),[level,setLevel]=useState(null),[questions,setQ]=useState([]),[ans,setAns]=useState({}),[files,setFiles]=useState({}),[step,setStep]=useState("info"),[msg,setMsg]=useState("");const j=useJob(job);
useEffect(()=>{if(j?.status==="completed"){if(j.result?.suggested_level){setLevel(j.result.suggested_level);setStep("waiting")}if(j.result?.questions)setQ(j.result.questions)}if(j?.status==="failed")setMsg(j.error)},[j]);
async function submitInfo(){const r=await fetch(API+"/admin/level-suggestion",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(c)}).then(x=>x.json());setAid(r.assessment_id);setJob(r.job_id);setStep("waiting")}
async function check(){const r=await fetch(API+"/user/"+aid+"/assessment").then(x=>x.json());if(r.questions_approved){setLevel(r.level);setQ(r.questions);setStep("test")}else{setLevel(r.level);setMsg(r.level?"Level "+r.level+" approved. Waiting for question approval.":"Waiting for administrator level approval.")}}
async function start(){const r=await fetch(API+"/user/"+aid+"/start",{method:"POST"}).then(x=>x.json());if(r.accepted)setStep("test");else setMsg(r.reason)}
async function submit(){for(const q of questions){const file=files[q.id];if(file){const form=new FormData();form.append("assessment_id",aid);form.append("task_id",q.id);form.append("media",file);await fetch(API+"/evidence",{method:"POST",body:form})}}const payload={assessment_id:aid,qp_code:"CON/Q0603",nsqf_level:level,candidate:c,answers:questions.map(q=>({...q,response:ans[q.id]||"",selected_option:q.type==="mcq"?Number(ans[q.id]):-1})),practical_scores:[]};const r=await fetch(API+"/submissions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}).then(x=>x.json());setMsg(r.accepted?"Submitted. Assessment is now locked to one attempt.":"Submission failed: "+r.reason);if(r.accepted)setStep("done")}
return <Shell title="Worker Dashboard"><section>{step==="info"&&<><h1>Recognition of Prior Learning</h1><p>Tell us about your prior work experience. The administrator will review the AI-assisted NSQF recommendation.</p><input placeholder="Name"value={c.name}onChange={e=>setC({...c,name:e.target.value})}/><input type="number"placeholder="Age"value={c.age}onChange={e=>setC({...c,age:+e.target.value})}/><input type="number"placeholder="Years experience"value={c.years_experience}onChange={e=>setC({...c,years_experience:+e.target.value})}/><input placeholder="Occupation"value={c.occupation}onChange={e=>setC({...c,occupation:e.target.value})}/><textarea placeholder="Work performed / skills"value={c.work_context}onChange={e=>setC({...c,work_context:e.target.value})}/><textarea placeholder="Prior training / certificates"value={c.prior_training}onChange={e=>setC({...c,prior_training:e.target.value})}/><button onClick={submitInfo}>Submit information</button></>}
{step==="waiting"&&<><h2>Awaiting administrator</h2><p>Assessment ID: <code>{aid}</code></p><p>AI suggested NSQF Level: <strong>{level||"processing"}</strong></p><button onClick={check}>Check assessment status</button></>}
{step==="test"&&<><h2>Assessment · NSQF Level {level}</h2><p>Starting the test locks the attempt. It cannot be restarted.</p><button onClick={start}>Start test</button>{questions.map(q=><article key={q.id}><small>{q.type} · {q.marks} marks</small><h3>{q.question}</h3>{q.type==="mcq"?(q.options||[]).map((o,i)=><label key={i}><input type="radio"name={q.id}checked={ans[q.id]===String(i)}onChange={()=>setAns({...ans,[q.id]:String(i)})}/>{o}</label>):q.type==="text"?<textarea placeholder="Write your answer"value={ans[q.id]||""}onChange={e=>setAns({...ans,[q.id]:e.target.value})}/>:<><p>Evidence required for this question. Upload the requested image/video.</p><input type="file"accept={q.type==="image"?"image/*":"video/*"}capture="environment"onChange={e=>setFiles({...files,[q.id]:e.target.files?.[0]})}/></>}</article>)}{questions.length>0&&<button onClick={submit}>Submit one attempt</button>}</>}
{step==="done"&&<><h2>Assessment submitted</h2><p>{msg}</p><p>The administrator will review AI evaluation and practical/image/video evidence.</p></>}{msg&&step!=="done"&&<p className="notice">{msg}</p>}</section></Shell>}
function Admin(){const[aid,setAid]=useState(""),[a,setA]=useState(null),[suggest,setS]=useState(null),[level,setLevel]=useState(4),[questions,setQ]=useState([]),[job,setJob]=useState(""),[msg,setMsg]=useState("");const j=useJob(job);useEffect(()=>{if(j?.status==="completed"){if(j.result?.suggested_level){setS(j.result);setLevel(j.result.suggested_level)}if(j.result?.questions)setQ(j.result.questions)}if(j?.status==="failed")setMsg(j.error)},[j]);
async function load(){const r=await fetch(API+"/admin/candidate/"+aid).then(x=>x.json());if(!r.candidate){setMsg("Candidate not found");return}setA(r.candidate?JSON.parse(r.candidate):{});setLevel(r.level||4);setS(r.level_suggestion?JSON.parse(r.level_suggestion):null);setQ(r.questions?JSON.parse(r.questions):[])}
async function suggestLevel(){const r=await fetch(API+"/admin/level-suggestion",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(a)}).then(x=>x.json());setAid(r.assessment_id);setJob(r.job_id)}
async function approve(){await fetch(API+"/admin/level-approval",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assessment_id:aid,nsqf_level:level,candidate:a,suggestion:suggest})});setMsg("Level approved.")}
async function generate(){const r=await fetch(API+"/admin/questions/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assessment_id:aid,nsqf_level:level,candidate:a,count:10})}).then(x=>x.json());setJob(r.job_id);setMsg("Groq question generation started.")}
async function approveQ(){await fetch(API+"/admin/questions/approve",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assessment_id:aid,questions}));setMsg("Questions and marking scheme approved. Test is active for worker.")}
return <Shell title="Admin Dashboard"><section><h1>RPL Administration</h1><div className="bar"><input placeholder="Assessment ID"value={aid}onChange={e=>setAid(e.target.value)}/><button onClick={load}>Load</button></div>{a&&<><h2>Worker declaration</h2><pre>{JSON.stringify(a,null,2)}</pre>{suggest&&<div className="result"><h2>AI NSQF recommendation</h2><h1>Level {suggest.suggested_level}</h1><p>Confidence: {suggest.confidence}</p><p>{suggest.reason}</p><label>Approved level<input type="number"min="1"max="8"value={level}onChange={e=>setLevel(+e.target.value)}/></label><button onClick={approve}>Approve level</button></div>}<button onClick={suggestLevel}>Run Groq level analysis</button><hr/><h2>AI question generation</h2><p>Level {level} module context is injected into the backend prompt.</p><button onClick={generate}>Generate questions</button>{questions.length>0&&<div><h2>Review / edit questions</h2>{questions.map((q,i)=><article key={q.id}><input value={q.question}onChange={e=>{const x=[...questions];x[i]={...q,question:e.target.value};setQ(x)}}/><select value={q.type||"mcq"}onChange={e=>{const x=[...questions];x[i]={...q,type:e.target.value};setQ(x)}}><option>mcq</option><option>text</option><option>image</option><option>video</option></select><input type="number"min="1"max="10"value={q.marks||1}onChange={e=>{const x=[...questions];x[i]={...q,marks:+e.target.value};setQ(x)}}/><button onClick={()=>setQ(questions.filter(x=>x.id!==q.id))}>Delete</button></article>)}<button onClick={()=>setQ([...questions,{id:"q-"+Date.now(),type:"text",question:"New question",options:[],marks:1}])}>Add question</button><button onClick={approveQ}>Approve & activate test</button></div>}</>}{msg&&<p className="notice">{msg}</p>}</section></Shell>}
function Shell({title,children}){return <main><header><div><strong>{title}</strong><span>AI-Assisted Recognition of Prior Learning</span></div><nav><a href="/">Worker</a> · <a href="/?admin=1">Admin</a></nav></header>{children}</main>}
function App(){return new URLSearchParams(location.search).has("admin")?<Admin/>:<Worker/>}createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);